CI: fix invalid name for artifact
Namely:
```
Error: The artifact name is not valid: archives-linux/amd64-x86_64. Contains the following character:  Forward slash /

Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /

These characters are not allowed in the artifact name due to limitations with
certain file systems such as NTFS. To maintain file system agnostic behavior,
these characters are intentionally not allowed to prevent potential problems
with downloads on different file systems.
```